main/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
]

portfolio_web/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('main.urls')),
    path('projects/', include('projects.urls')),
    path('ratings/', include('ratings.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns.append(re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}))
    urlpatterns.append(re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}))

projects/urls.py
from django.urls import path

from .views import *


app_name = 'projects'

urlpatterns = [
    path('', projects, name='projects'),
    path('<int:id>/', project, name='project'),
    path('list/', ProjectsView.as_view(), name='projects_list'),
]

main/models.py
from django.db import models


class Page(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.CharField(max_length=100, unique=True)
    reverse_url = models.CharField(max_length=100, blank=True)
    order = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['order']

    def __str__(self) -> str:
        return self.name
    
    def get_url(self):
        return self.reverse_url + self.slug
    

class Contact(models.Model):
    name = models.CharField(max_length=100, unique=True)
    value = models.CharField(max_length=100, unique=True)
    order = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['order']

    def __str__(self) -> str:
        return self.name


class Settings(models.Model):
    name = models.CharField(max_length=100, unique=True)
    pages = models.ManyToManyField(Page)
    page_title = models.CharField(max_length=50, blank=True)
    contacts = models.ManyToManyField(Contact)
    image = models.ImageField(upload_to="images/", blank=True)

    def __str__(self) -> str:
        return self.name

main/forms.py
from django import forms
from django.core.validators import EmailValidator


class ContactForm(forms.Form):
    name = forms.CharField(
        required=True, 
        max_length=100, 
        widget=forms.widgets.TextInput(attrs={"placeholder": "Imię", "class": "form-control"}), 
        label="",
        error_messages={
            'required': 'Proszę podać imię',
            'max_length': 'Imię nie może mieć więcej niż 100 znaków'
        }
    )
    email = forms.EmailField(
        required=True, 
        widget=forms.widgets.TextInput(attrs={"placeholder": "Email", "class": "form-control"}), 
        label="",
        error_messages={
            'required': 'Proszę podać email',
            'invalid': 'Niepoprawny adres email'
        }
    )
    subject = forms.CharField(
        required=True, 
        max_length=100, 
        widget=forms.widgets.TextInput(attrs={"placeholder": "Temat", "class": "form-control"}), 
        label="",
        error_messages={
            'required': 'Proszę podać temat',
            'max_length': 'Temat nie może mieć więcej niż 100 znaków'
        }
    )
    message = forms.CharField(
        required=True, 
        widget=forms.widgets.Textarea(attrs={
            "placeholder": "Wiadomość",
            "class": "form-control",
            "rows": 5,
            "cols": 40,
            "style": "resize: none;"
            }), 
        label="",
        error_messages={
            'required': 'Proszę napisać wiadomość'
        }
    )

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if self.errors.get(field_name):
                field.widget.attrs['class'] += ' is-invalid'

main/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.mail import EmailMessage

from projects.models import Tag
from .models import Settings
from .forms import ContactForm


def home(request):
    settings = Settings.objects.first()
    return render(request, "home.html", {'active_tab': 'home', 'settings': settings})


def about(request):
    settings = Settings.objects.first()
    tags = Tag.objects.filter(show_about=True)
    return render(request, "about.html", {'active_tab': 'about', 'settings': settings, 'tags': tags})


def contact(request):
    settings = Settings.objects.first()
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']

            try:
                email_message = EmailMessage(
                    f"{subject}",
                    f"{name} | {email}\n\n{message}",
                    "mirrovex@wp.pl",  # send from
                    ["mirrovex@wp.pl"],  # send to
                    reply_to=[email]
                )
                email_message.send(fail_silently=False)


                messages.success(request, "Wysłano wiadomość")
                return redirect("contact")
            except Exception as e:
                print(e)
        messages.error(request, "Twój formularz ma błędy")
        return render(request, "contact.html", {'active_tab': 'contact', 'settings': settings, 'form': form})
    else:
        form = ContactForm()
        return render(request, "contact.html", {'active_tab': 'contact', 'settings': settings, 'form': form})

main/templates/about.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    O mnie
{% endblock title %}


{% block extrahead %}
    <link rel="stylesheet" href="{% static 'css/about.css' %}">
{% endblock extrahead %}
    

{% block content %}
    <div class="container flexrow">
        <div class="left-container flexcol">
            <div class="image-container">
                <img src="{{ settings.image.url }}" class="profile-image" />
            </div>
            <h1 class="tag-title">Technologie</h1>
            <div class="tag-container flexrow">
                {% for tag in tags %}
                    <button class="btn btn-secondary tag" data-tag="{{ tag.name|lower }}" disabled>
                        {% if tag.get_image_url %}
                            <img src="{{ tag.get_image_url }}" class="icon" style="{{ tag.style }}" />
                        {% endif %}
                        {{ tag.name }}
                    </button>
                {% endfor %}
            </div>
        </div>
        <div class="right-container flexcol">
            <div class="text-container">
                <p>
                    Swoją przygodę z programowaniem rozpocząłem jeszcze jako dziecko, tworząc i programując własne roboty LEGO Mindstorms.
                    Już wtedy świat technologii wydawał mi się fascynujący i pociągający. Od tamtej pory systematycznie rozwijam swoje
                    umiejętności, zdobywając wiedzę zarówno w zakresie języków programowania, jak i powiązanych technologii.
                </p>
                <p>
                    Wielu języków programowania, analitycznego myślenia, rozwiązywania problemów, bibliotek, algorytmów i innych zagadnień
                    nauczyłem się samodzielnie, więc zdecydowanie mogę powiedzieć, że szybkie przyswajanie nowej wiedzy jest jedną z moich
                    zalet. Człowiek jednak uczy się przez całe życie, więc i ja nigdy nie przestałem się uczyć. Aktualnie uczęszczam do
                    międzynarodowej szkoły programowania <a href="https://42warsaw.pl/">42Warsaw</a> i tworzę własne projekty usprawniające codzienne czynności.
                </p>
                <p>
                    W Pythonie programuję od 2018 roku, w Javie (Android) od 2020 roku, a HTML, CSS i JavaScript od 2021 roku.
                    Frameworku Django zacząłem używać dopiero w 2023 roku, ale dzięki zaawansowanej znajomości Pythona, szybko go opanowałem.
                    To pozwoliło mi na zdobycie swojej pierwszej pełnowymiarowej pracy jako programista oraz stworzenie tej strony.
                </p>
                <p>
                    Zawsze jestem zaangażowany w projekt i często wpadam na pomysły, jak można usprawnić działanie programu lub jakie
                    dodatkowe funkcje można do niego dodać. Moja kreatywność i chęć ciągłego rozwoju wpływają na to, że często stawiam przed
                    sobą nowe wyzwania. Nawet gdy zdarzy się sytuacja, że czegoś nie wiem, szybko znajduję potrzebne informacje i poszerzam
                    swoją wiedzę.
                </p>
                <p>
                    Dodatkowo, od kilku lat jestem mistrzem gry w grach RPG i właścicielem jednego z największych polskich serwerów do
                    grania w gry fabularne na Discordzie. W wolnym czasie, poza programowaniem, wymyślam scenariusze i prowadzę sesje, co
                    jeszcze bardziej rozwija moją kreatywność oraz umiejętności komunikacyjne.
                </p>
            </div>
            <div class="icon-container">
                <a class="icon-link" href="https://github.com/Mirrovex">
                    <img src="{% static 'icons/github-mark.png' %}" class="medium-icon github-icon" />
                </a>
                <a class="icon-link" href="https://linkedin.com/in/filip-mickiewicz">
                    <img src="{% static 'icons/linkedin.png' %}" class="medium-icon linkedin-icon" />
                </a>
            </div>
        </div>
    </div>
{% endblock content %}

main/templates/base.html
{% load static %}

<!doctype html>
<html lang="pl">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {{ settings.page_title }}
        {% block title %}
            Strona główna
        {% endblock title %}
    </title>
    <link rel="icon" href="{% static 'icons/pantera-icon.png' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    
    {% block extrahead %}
        
    {% endblock extrahead %}
        
  </head>
  <body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
            <div class="container-fluid">
                <div class="name_div">
                    <img src="{% static 'icons/pantera.jpg' %}" class="logo" />
                    <a class="navbar-brand" href="{% url 'home' %}">Filip Mickiewicz</a>
                </div>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    {% for page in settings.pages.all %}
                        <li class="nav-item">
                          <a class="nav-link {% if active_tab == page.slug %}active{% endif %}" href="{% url page.get_url %}">{{ page.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
              </div>
            </div>
          </nav>
    </header>
    <main>
      <div class="col-md-10 offset-md-1 base-div">
        <br>
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% endfor %}
        {% endif %}
        
        {% block content %}
        {% endblock content %}
      </div>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    {% block extra_js %}
    {% endblock extra_js %}
  </body>
</html>

main/templates/contact.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    Kontakt
{% endblock title %}


{% block extrahead %}
    <link rel="stylesheet" href="{% static 'css/contact.css' %}">
{% endblock extrahead %}
    

{% block content %}
    <div class="container flexrow">
        <div class="text-container flexcol">
            <h1>Masz zlecenie?</h1>
            <h2>Napisz do mnie</h2>
            <h2>--></h2>
        </div>
        <div class="form-container flexrow">
            <form class="email-form" method="POST" action="{% url 'contact' %}">
                {% csrf_token %}
        
                {% for field in form %}
                    <div class="form-field-container">
                        {{ field }}
                        {% if field.errors %}
                            <div id="validationServerUsernameFeedback" class="invalid-feedback">
                                {{ field.errors }}
                            </div>
                        {% endif %}
                    </div>
                {% endfor %}
                <div class="button-container flexrow">
                    <div class="loading-container">
                    </div>
                    <button type="submit" class="btn btn-primary send-email">Wyślij</button>
                </div>
            </form>
            <div class="info-container flexcol">
                <div class="info-text-container">
                    {% for contact in settings.contacts.all %}
                        <h4>{{ contact.name }}</h4>
                        <p>{{ contact.value }}</p>
                    {% endfor %}
                </div>
                <div class="icon-container">
                    <a class="icon-link" href="https://github.com/Mirrovex">
                        <img src="{% static 'icons/github-mark.png' %}" class="medium-icon github-icon" />
                    </a>
                    <a class="icon-link" href="https://linkedin.com/in/filip-mickiewicz">
                        <img src="{% static 'icons/linkedin.png' %}" class="medium-icon linkedin-icon" />
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}


{% block extra_js %}
    <script src="{% static 'js/contact.js' %}"></script>
{% endblock extra_js %}

main/templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    Strona Główna
{% endblock title %}


{% block extrahead %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock extrahead %}
    

{% block content %}
    <div class="container">
        <h1>Cześć, jestem <span class="highlight">Filip Mickiewicz</span>,</h1>
        <h2>Fullstack Developer</h2>
        <div class="icon-container">
            <a class="icon-link" href="https://github.com/Mirrovex">
                <img src="{% static 'icons/github-mark.png' %}" class="medium-icon github-icon" />
            </a>
            <a class="icon-link" href="https://linkedin.com/in/filip-mickiewicz">
                <img src="{% static 'icons/linkedin.png' %}" class="medium-icon linkedin-icon" />
            </a>
        </div>
        <div class="button-container">
            <a class="empty-button" href="{% url 'projects:projects' %}">
                Moje projekty
                <span class="arrow">➜</span>
            </a>
        </div>
    </div>
    <footer>
        Strona zrobiona przez Filipa Mickiewicza
    </footer>
{% endblock content %}


{% block extra_js %}
    <script src="https://cdn.jsdelivr.net/npm/canvas-confetti@1.6.0/dist/confetti.browser.js"></script>
    <script src="{% static 'js/home.js' %}"></script>
{% endblock extra_js %}
    